imAsparky/django-cookiecutter

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/documentation-request.md, .github/ISSUE_TEMPLATE/feature-request.md
Custom issue templates assist the creator provide information in
the correct format.
closes #1
=> docs(issue): Add custom templates #1

.pre-commit-config.yaml, requirements_dev.txt
Provide the ability to check code before its committed.
closes #7
=> feat(pre-commit): Add pre-commit-config  #7

README.rst
* Codacy provides provides potential users information about the projects
quality.
* Pre-commit badge added.
* Repo status badge added.
closes #9
=> feat(codacy): Add Codacy integration and badge #9

.gitignore, .readthedocs.yaml, README.rst, docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/index.rst, docs/source/requirements.txt, setup.cfg
Users require information about how to use the project.
closes #10
=> docs(sphinx): Add Sphinx and Readthedocs #10

.gitignore, docs/source/conf.py, docs/source/discussion/index-discussion.rst, docs/source/doc-templates/index-templates.rst, docs/source/doc-templates/rendered-template-tutorial.rst, docs/source/doc-templates/template-index.rst, docs/source/doc-templates/template-tutorial.rst, docs/source/how-tos/index-how-to.rst, docs/source/index.rst, docs/source/reference/index-reference.rst, docs/source/tutorials/index-tutorials.rst, requirements_dev.txt
Providing a document framework for contributors encourages consistent
documentation format and style.
closes #17
=> docs(diataxis): Add document framework #17

cookiecutter.json, hooks/post_gen_project.py, hooks/pre_gen_project.py
Very basic setup, mostly ready for GitHub workflows.
closes #25
=> chore(cookie): Add cookiecutter.json and Hooks #25

.github/ISSUE_TEMPLATE/delete.txt, cookiecutter.json, hooks/post_gen_project.py, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/.github/ISSUE_TEMPLATE.md, {{cookiecutter.git_project_name}}/.github/ISSUE_TEMPLATE/bug-report.md, {{cookiecutter.git_project_name}}/.github/ISSUE_TEMPLATE/chore.md, {{cookiecutter.git_project_name}}/.github/ISSUE_TEMPLATE/documentation-request.md, {{cookiecutter.git_project_name}}/.github/ISSUE_TEMPLATE/feature-request.md
Assists users in providing the information required when submitting
an issue.
closes #31
=> docs(issue): Add custom issue templates #31

cookiecutter.json, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/README.rst
A README provides potential users information about a project.
closes #39
=> docs(django): Add readme with badges and license #39

README.rst, cookiecutter.json, hooks/post_gen_project.py, tests/test_bake_django.py, tests/test_helper.py
Git initialise, and initial commit is more consistent.
closes #47
=> feat(django): Add git init and initial commit #47

README.rst, cookiecutter.json, hooks/post_gen_project.py, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/.github/workflows/test_contribution.yaml
Ensure tests pass before merging Django project to main.
closes #49
=> feat(django): Add GH action test workflow #49

cookiecutter.json, hooks/post_gen_project.py, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/.pyup.yaml, {{cookiecutter.git_project_name}}/README.rst
Keep dependencies up to date, pyup uses Conventional commits now.
closes #58
=> feat(django): Add pyup checks and badge #58

.pyup.yaml, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/.pyup.yaml
PR and commits messages where incorrectly formatted.
closes #60
=> fix(pyup): Update pr_prefix for Conventional commits #60

hooks/post_gen_project.py
post_gen.py had bocome very messy and difficult to read.
closes #62
=> refactor(cookie): File and Directory deletion simplified #62

.pre-commit-config.yaml, {{cookiecutter.git_project_name}}/.pre-commit-config.yaml
Reduce the amount of monotonous update work.
closes #77
=> feat(django): Add django-update and pyupgrade to pre-commit #77

README.rst, cookiecutter.json, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/requirements_dev.txt, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/settings.py, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/urls.py
Django-allauth simplifies authentication.
closes #79
=> feat(django): Add use django-allauth option  #79

{{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/settings.py
A basic Django security feature.
closes #80
=> feat(django): Add django env DJANGO_SECRET_KEY #80

hooks/post_gen_project.py, {{cookiecutter.git_project_name}}/README.rst, {{cookiecutter.git_project_name}}/docs/source/tutorials/index-tutorials.rst, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/settings.py, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/urls.py
settings.py line 90 missing ]
README spacings are very cramped.
The tutorials index needs a cookiecutter template for the new project.
urls.py needs to import include as well.
post_gen remove print debug
closes #83
=> fix(cookie): Small bug fixes in generated Django #83

cookiecutter.json, docs/source/how-tos/how-to-quickstart.rst, docs/source/how-tos/index-how-to.rst
Quickstart provides a brief explanation of each input.
closes #85
=> docs(cookie): Add how-to quickstart Django Cookiecutter #85

docs/source/tutorials/tutorial-create-django-project.rst
This tutorial gets new devs up and running.
closes #88
=> docs(tutorial): Add Create  Django Cookiecutter #88

{{cookiecutter.git_project_name}}/.gitignore
Files not required in VCS should be excluded.
closes #150
=> fix(git): Add .gitgnore to Django project #150

config/requirements/production.txt, {{cookiecutter.git_project_name}}/config/requirements/production.txt
Production dependencies hadn't been added.
closes # 145
=> fix(deps): Add Django production dependencies #145

{{cookiecutter.git_project_name}}/config/settings/base.py
=> fix(settings): correct DEBUG syntax #143

.gitignore, README.rst, cookiecutter.json, hooks/post_gen_project.py, {{cookiecutter.git_project_name}}/config/requirements/production.txt, {{cookiecutter.git_project_name}}/config/requirements/staging.txt, {{cookiecutter.git_project_name}}/config/settings/local.py, {{cookiecutter.git_project_name}}/config/settings/production.py, {{cookiecutter.git_project_name}}/config/settings/staging.py, {{cookiecutter.git_project_name}}/config/settings/test.py, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/asgi.py, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/wsgi.py
DATABASE{default} settings were prone to an error with the previous configurations.  Each settings environment now has the DB
settings for clarity.
closes #151
=> fix(settings): Move DB into relevant settings #151

cookiecutter.json, hooks/post_gen_project.py, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/.dockerignore, {{cookiecutter.git_project_name}}/Dockerfile, {{cookiecutter.git_project_name}}/compose/docker-compose-swarm.yml, {{cookiecutter.git_project_name}}/config/settings/base.py, {{cookiecutter.git_project_name}}/config/settings/local.py, {{cookiecutter.git_project_name}}/config/settings/production.py, {{cookiecutter.git_project_name}}/config/settings/staging.py, {{cookiecutter.git_project_name}}/config/settings/test.py, {{cookiecutter.git_project_name}}/docker-entrypoint.sh
The Dockerfile feature required several changes to settings and other
files to be workable.
Added a docker-compose file specifically for use in a docker swarm with
Traefik reverse proxy and docker secrets.
cookiecutter.json now re-organised,  flowing better during project set up.
closes #148
=> feat(docker): Add production ready Dockerfile #148

docs/source/how-tos/how-to-docker-linux-cheatsheet.rst, docs/source/how-tos/index-how-to.rst
I have added some useful commands for Docker, Django and  Linux.
closes #149
=> docs(cli): Add CLI cheatsheet #149

{{cookiecutter.git_project_name}}/Dockerfile
A copy paste-error caused some cookiecutter variables to be missing in the
Dockerfile.
closes #196
=> fix(typo): Changed to cookiecutter variable #196

docs/source/tutorials/new-django-project-options.txt, docs/source/tutorials/tutorial-create-django-project.rst, docs/source/tutorials/tutorial-segment-create-env-variable.rst
After a new users feedback, improvements to the tutorial are
implemented.
closes #188
=> docs(tutorial): Improve django-cookiecutter #188

README.rst, docs/source/reference/index-reference.rst, docs/source/reference/reference-docker-file.rst
A reference for the critical points of the Dockerfile is required to
improve the user experience.
closes #147
=> docs(docker): Add Dockerfile reference #147

cookiecutter.json, docs/source/reference/reference-project-inputs.rst
The project reference documentation was out of date.
closes #215
=> docs(reference): Update project inputs #215

{{cookiecutter.git_project_name}}/config/settings/test.py
Debug settings had been incorrectly assigned and incorrectly typed.
closes #220
=> fix(tests): Fix test DEBUG settings typo's #220

README.rst, cookiecutter.json, docs/source/how-tos/how-to-custom-user.rst, docs/source/how-tos/index-how-to.rst, docs/source/tutorials/new-django-project-options.txt, docs/source/tutorials/tutorial-create-django-project.rst, hooks/post_gen_project.py, tests/test_bake_django.py, {{cookiecutter.git_project_name}}/README.rst, {{cookiecutter.git_project_name}}/config/requirements/base.txt, {{cookiecutter.git_project_name}}/config/requirements/production.txt, {{cookiecutter.git_project_name}}/config/requirements/test.txt, {{cookiecutter.git_project_name}}/config/settings/base.py, {{cookiecutter.git_project_name}}/conftest.py, {{cookiecutter.git_project_name}}/pytest.ini, {{cookiecutter.git_project_name}}/tests/test_custom_user.py, {{cookiecutter.git_project_name}}/tox.ini, {{cookiecutter.git_project_name}}/users/admin.py, {{cookiecutter.git_project_name}}/users/apps.py, {{cookiecutter.git_project_name}}/users/forms.py, {{cookiecutter.git_project_name}}/users/models.py, {{cookiecutter.git_project_name}}/users/views.py, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/urls.py
* Django admin is missing some useful security features, e.g. read-only
on critical fields.
* A custom user model that extends the existing user model will allow some
additional flexibility to customise the user.
* Added django project custom user test suite and fixtures.
* Added a custom user how-to.
* Updated django-cookiecutter test suite.
* Updated tutorial-create-django-project.
* Updated README
closes #207
closes #212
=> feat(user): Add custom user and admin #207

tests/test_bake_django.py, {{cookiecutter.git_project_name}}/.env/.local, {{cookiecutter.git_project_name}}/.env/.testing, {{cookiecutter.git_project_name}}/.github/workflows/test_contribution.yaml, {{cookiecutter.git_project_name}}/.pre-commit-config.yaml, {{cookiecutter.git_project_name}}/LICENSE.rst, {{cookiecutter.git_project_name}}/compose/docker-compose-swarm.yml, {{cookiecutter.git_project_name}}/config/settings/base.py, {{cookiecutter.git_project_name}}/config/settings/local.py, {{cookiecutter.git_project_name}}/config/settings/production.py, {{cookiecutter.git_project_name}}/config/settings/staging.py, {{cookiecutter.git_project_name}}/config/settings/test.py, {{cookiecutter.git_project_name}}/requirements_dev.txt, {{cookiecutter.git_project_name}}/templates/account/password_reset_done.html, {{cookiecutter.git_project_name}}/tox.ini, {{cookiecutter.git_project_name}}/users/admin.py, {{cookiecutter.git_project_name}}/users/apps.py, {{cookiecutter.git_project_name}}/users/forms.py, {{cookiecutter.git_project_name}}/users/models.py, {{cookiecutter.git_project_name}}/{{cookiecutter.project_slug}}/urls.py
The pre-commit config was not working in the Django project.
Remove pylint: The config was not changing pylint action.  Time to fix
didnt provide any additional value.
Flake8: Update the config and now it is working nicely with Django.
Fix all formatting errors in the Django project.
closes #256
closes #255
=> fix(django): Pre-commit  Flake8 and pylint fixed #256

{{cookiecutter.git_project_name}}/config/requirements/base.txt, {{cookiecutter.git_project_name}}/config/settings/base.py
The local dev CLI output has more information and nice formatting
using `rich` cli formatter.
closes #263
=> feat(dev): Improve local dev CLI logging output #263

README.rst, cookiecutter.json, docs/source/how-tos/how-to-docker-linux-cheatsheet.rst, docs/source/how-tos/how-to-quickstart.rst, docs/source/how-tos/how-to-tailwind.rst, docs/source/how-tos/index-how-to.rst, docs/source/reference/reference-docker-file.rst, docs/source/tutorials/tutorial-create-django-project.rst, {{cookiecutter.git_project_name}}/config/requirements/base.txt, {{cookiecutter.git_project_name}}/config/requirements/local.txt, {{cookiecutter.git_project_name}}/config/settings/base.py, {{cookiecutter.git_project_name}}/config/settings/local.py, {{cookiecutter.git_project_name}}/core/urls.py, {{cookiecutter.git_project_name}}/templates/base.html, {{cookiecutter.git_project_name}}/theme/apps.py, {{cookiecutter.git_project_name}}/theme/static_src/.gitignore, {{cookiecutter.git_project_name}}/theme/static_src/package.json, {{cookiecutter.git_project_name}}/theme/static_src/postcss.config.js, {{cookiecutter.git_project_name}}/theme/static_src/src/styles.css, {{cookiecutter.git_project_name}}/theme/static_src/tailwind.config.js, {{cookiecutter.git_project_name}}/theme/templates/base.html
* Added django-tailwind.
* Added django-tailwind How-to.
* Updated README.
* Updated quickstart.
* Updated django-cookiecutter tutorial.
* Removed django_htmx.middleware.HtmxDetails from middleware, it was
causing errors.
* Added new tests for the cookiecutter build process.
closes #277
=> feat(css): Add django-tailwind and documentation #277

{{cookiecutter.git_project_name}}/config/settings/base.py
=> chore(settings): Remove unnecessary comments #317

.pre-commit-config.yaml, {{cookiecutter.git_project_name}}/.pre-commit-config.yaml
=> chore(pre-com): Update config files #320

docs/source/how-tos/how-to-test-env-settings.rst, {{cookiecutter.git_project_name}}/tests/conftest.py
Adds a simple and consistent way to override settings for tests.
closes #349
=> feat(test): Add override settings to conftest #349

.github/workflows/test_contribution.yaml
=> chore(actions): Update GH checkout and setup #527

.github/workflows/test_contribution.yaml, config/requirements/base.txt, {{cookiecutter.git_project_name}}/config/requirements/base.txt
=> chore(deps): Update cookiecutter and Django #527

{{cookiecutter.git_project_name}}/tox.ini
=> chore(pypy): Update to 3.9 #530

.github/workflows/semantic_release.yaml, .github/workflows/test_contribution.yaml, README.rst, tox.ini
=> chore(tox): Simplify python version support to 311 #532

.github/workflows/test_contribution.yaml
=> chore(action): Simplfy GH test_contributions #534

.pre-commit-config.yaml
=> chore(pre-commit): Updated #536

{{cookiecutter.git_project_name}}/config/requirements/base.txt
=> fix(deps): Update Django to 4.2.1 #558

.github/workflows/semantic_release.yaml
relekang had a bug in a master version. That has been fixed and now needs to have the pinned version changed back to master
closes #562
=> chore(deps): Revert relekang to @master #562

{{cookiecutter.git_project_name}}/Dockerfile
Update python version and Ubuntu packages.
closes # 600
=> chore(build): Update Dockerfile #600

{{cookiecutter.git_project_name}}/config/settings/base.py
The MEDIA settings in base.py where missing for some reason.
closes #604
=> fix(settings): Add missing MEDIA settings #604

pyproject.toml
Shields.io can now make use of pyproject.toml settings for creating badges.
closes #651
=> chore(config): Add pyproject.toml settings #651

pyproject.toml, requirements_dev.txt
The docs requirements are needed for documentation, particularly if using vscode and esbonio server.
closes #653
=> chore(deps): Add doc requirements to dev #653

README.rst, docs/source/extras.rst.txt, docs/source/how-tos/how-to-contribute.rst, docs/source/how-tos/how-to-logging.rst, docs/source/how-tos/how-to-quickstart.rst, docs/source/how-tos/how-to-test-env-settings.rst, docs/source/tutorials/tutorial-segment-create-env-variable.rst
Updated various docs for:
Versions supported
Changes to configs
closes #648
closes #635
=> docs(cookie): Update to current times #648

{{cookiecutter.git_project_name}}/templates/base.html
=> chore(deps): Update alpine and htmx cdn #631

{{cookiecutter.git_project_name}}/core/utils/context_processors.py, {{cookiecutter.git_project_name}}/tests/conftest.py, {{cookiecutter.git_project_name}}/tests/test_custom_user.py
Ensure the correct user model is used.  Importing CustomUser is not robust.
closes #661
=> refactor(user): Update user=get_user_model #661

{{cookiecutter.git_project_name}}/docker-entrypoint.sh
Added checks for Database Environment variables and feedback to the user on what is happening in process of connecting to Postgres.
closes #658
=> fix(shell): Docker entrypoint improvement #658

{{cookiecutter.git_project_name}}/core/management/commands/nuke_db_sqlite.py, {{cookiecutter.git_project_name}}/docs/source/how-to-guides/{{cookiecutter.git_project_name}}/how-to-user-session-data-add.rst
A management command to remove all migrations, delete dbsqlite,
makemigrations and migrate.  This is only available in local dev and
DEBUG.
closes #669
=> feat(dev): Add nuke command to start fresh migrations and db #669

README.rst, docs/source/how-tos/how-to-quickstart.rst
=> docs(ver): Update to reflect Django 5 #746

{{cookiecutter.git_project_name}}/.readthedocs.yaml
=> chore(rtd): Update yaml file with  os #750

{{cookiecutter.git_project_name}}/core/views/generic/base.py
The template check was checking or when and was the correct one.
closes #675
=> fix(core): Update template check logic #675

tests/test_bake_django.py, {{cookiecutter.git_project_name}}/config/requirements/base.txt, {{cookiecutter.git_project_name}}/config/requirements/test.txt, {{cookiecutter.git_project_name}}/config/settings/base.py
=> chore(auth): Update settings for dj-allauth #762 

docs/source/reference/reference-docker-file.rst, docs/source/tutorials/tutorial-create-GH-repo.rst, docs/source/tutorials/tutorial-create-django-project.rst, pyproject.toml
=> docs(ver): Review and update versions and typos #774
