imAsparky/django-cookiecutter

.github/.git-commit-template.txt
README.md
README.rst

A conventional commits message template will assist contributors
to provide information in a standard format.
closes #2

docs(commit): Add conventional commits msg #2

---

README.rst
docs/source/code-of-conduct.rst
docs/source/how-tos/how-to-contribute.rst

Missing docstring example, so this was included.
Also README links to Contributing and CoC fixed.
Fixed typo's in Code of Conduct.
closes #23

docs(how-to): Add context to Contributing #23

---

cookiecutter.json
hooks/post_gen_project.py
tests/test_bake_django.py
{{cookiecutter.git_project_name}}/.github/.git-commit-template.txt

Assists users in providing the information required in a consistent
format when making git commits.  The Conventional Commits format is
necessary for python semantic versioning to work correctly.
closes #33

docs(git): Add Conventional Commits msg template #33

---

LICENSE.rst
hooks/post_gen_project.py
hooks/pre_gen_project.py
tests/test_bake_django.py
tox.ini
{{cookiecutter.git_project_name}}/LICENSE.rst

Five options for LICENSE selection are now available to the user.
closes #37

docs(django): Add select a license option #37

---

README.rst
cookiecutter.json
docs/source/readme.rst
hooks/post_gen_project.py
tests/test_bake_django.py
{{cookiecutter.git_project_name}}/.readthedocs.yaml
{{cookiecutter.git_project_name}}/README.rst

Read the Docs is a standard document deployment service.
closes #43

feat(django): Add Read the Docs config and badge #43

---

README.rst
cookiecutter.json
hooks/post_gen_project.py
tests/test_bake_django.py
{{cookiecutter.git_project_name}}/.github/semantic.yaml
{{cookiecutter.git_project_name}}/.github/workflows/semantic_release.yaml
{{cookiecutter.git_project_name}}/CHANGELOG.md
{{cookiecutter.git_project_name}}/README.rst

Using semantic-release as a GitHub action removes possible
release inconsistencies.
closes #45

feat(django): Add semantic-release GH action #45

---

.pyup.yaml
README.rst
{{cookiecutter.git_project_name}}/requirements_dev.txt

Keep dependencies up to date, pyup uses Conventional commits now.
closes #53

feat(cookie): Add pyup checks and badge #53

---

docs/source/how-tos/how-to-quickstart.rst
docs/source/reference/index-reference.rst
docs/source/reference/reference-project-inputs.rst
docs/source/tutorials/tutorial-create-django-project.rst

Quickstart was not the place for all the project reference information.
closes #92

docs(reference): Move options from How-to to Reference #92

---

tests/test_bake_django.py

The test for django-allauth was not robust and failed when the package
was updated.  The test now checks "django-allauth==" as a string in the
requirements file.
closes #178

fix(test): Django-alluth test improved #178

---

README.rst
{{cookiecutter.git_project_name}}/config/settings/base.py

fix(deps): Django 4.0 ugetext update to gettext #181
Features removed in 4.0¶
These features have reached the end of their deprecation cycle and are
removed in Django 4.0.
django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(),
ungettext(), and ungettext_lazy()
closes #181

fix(deps): Django 4.0 ugetext update to gettext #181

---

{{cookiecutter.git_project_name}}/config/settings/local.py

Django debug-toolbar requires ugettext_lazy.  Django 4.0 does not
support that anymore.  Debug toolbar is disabled in
config/settings/local.py until it runs on Django 4.0.
closes #191

fix(deps): Debug toolbar disabled until update #191

---

cookiecutter.json
tests/test_bake_django.py
{{cookiecutter.git_project_name}}/config/settings/base.py

L10N is on by default and is deprecated in Django 4.0. Django dev will
drop the option on Django 5.0. The project setup is now more
straightforward.
closes #183

fix(options): Remove L10N choice from set-up #183

---

{{cookiecutter.git_project_name}}/config/settings/base.py

Django did not recognise changes in the allauth templates.
Django could not find the allauth templates new location when added to
the Project folder.
"DIRS": [os.path.join(BASE_DIR, "templates")] added to TEMPLATES to
tell Django where to look for HTML templates.
closes #199

fix(templates): Add templates/ to TEMPLATES #199

---

hooks/post_gen_project.py
tests/test_bake_django.py

Selecting django-allauth=n did not remove django-allauth templates from
the project/templates folder.
templates/account now removed when selecting django-allauth=n.
Tests are written to cover this action.
closes #200

fix(allauth): Templates deleted if allauth=n #200

---

{{cookiecutter.git_project_name}}/Dockerfile

These ENV lost in Dockerfile updates, now added back in.
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
closes #204

fix(Dockerfile): Add ENV's for PYTHON #204

---

docs/source/reference/reference-project-inputs.rst
tests/test_bake_django.py
{{cookiecutter.git_project_name}}/config/settings/base.py

These two settings are for django-allauth.
If use_django_allauth=n, delete these settings on project generation.
LOGIN_REDIRECT_URL = "/admin/"
LOGOUT_REDIRECT_URL = '/accounts/login/'
closes #213

fix(project): Remove LOGIN/LOGOUT from settings #213

---

tests/test_bake_django.py
{{cookiecutter.git_project_name}}/requirements_dev.txt
{{cookiecutter.git_project_name}}/tox.ini

Tox provides a consistent test process.
closes #208

feat(project): Add tox.ini for testing #208

---

tests/test_bake_django.py

test_baked_django_with_docs_conf_settings_ok fails on "Year=2021"
closes #221

fix(tests): Replace "2021" with f"{current_year}" #221

---

docs/source/how-tos/how-to-quickstart.rst
{{cookiecutter.git_project_name}}/.env/.testing
{{cookiecutter.git_project_name}}/config/settings/test.py

Sometimes it is not convenient to run tests if a connection to a
PostgreSQL, MySQL or other DB is unavailable.
Local and or learning projects may not warrant a Production
grade Database.
Using an ENV to select between db.sqlite3 or a production database can
make the testing process easier.
closes #227

feat(test): Add test DB options def=sqlite #227

---

tox.ini

Items in command must be in tox env or whitelisted.
closes #229

chore(tox): Add whitelist_externals #229

---

tests/test_bake_django.py
{{cookiecutter.git_project_name}}/.gitignore
{{cookiecutter.git_project_name}}/config/requirements/test.txt
{{cookiecutter.git_project_name}}/setup.cfg
{{cookiecutter.git_project_name}}/tox.ini
{{cookiecutter.git_project_name}}/users/models.py

Added some better testing practices from Jame Bennetts
https://www.b-list.org/weblog/2020/feb/03/how-im-testing-2020/
Added artifact clean up after each test run.
Added pip upgrade for each environment.
Added test coverage.
Added setup.cfg for coverage configuration.
Updated .gitignore with coverage_html_report/.
Added cookiecutter test for tox.ini created ok.
closes #233

feat(tox): Add proj test coverage and cleanup #233

---

README.rst
docs/source/tutorials/tutorial-create-django-project.rst

Fix: Create Project tutorial was not in the index correctly.
Fix: Create Project tutorial broken link to Custom User.
Fix: README broken link to Custom User.
Improve: Create Project tutorial Troubleshooting section.
closes #235

fix(docs): Tutorial and README broken links #235

---

README.rst
docs/source/how-tos/how-to-test-env-settings.rst
docs/source/how-tos/index-how-to.rst

Add how-to change test DB settings document.
Update how-to index.
Add link to new how-to to README.
closes #239

docs(how-to): Add changing test DB settings #239

---

{{cookiecutter.git_project_name}}/config/settings/local.py

django-debug-toolbar supports Django 4.0 now.
closes #243

chore(deps): Re-instate debug-toolbar #243

---

{{cookiecutter.git_project_name}}/.pre-commit-config.yaml

Comment out Black and Flake8 exclude: empty exclude causes
pre-commit to raise an error.
closes #248

fix(django): Pre-commit Black and Flake8 exclude #248

---

hooks/post_gen_project.py

Initial commit message is bounded by "". Remove the quotations
closes #250

fix(git): Remove "" from initial commit message #250

---

.pre-commit-config.yaml
{{cookiecutter.git_project_name}}/.pre-commit-config.yaml

django-upgrade target version 4.0 had stopped working.
closes #252

fix(pre-commit): django-upgrade removed #252

---

{{cookiecutter.git_project_name}}/users/admin.py

The CustomUser admin create form was missing some fields
to make the creation of a new user easy.
closes #272

chore(user): Improve admin create user form #272

---

{{cookiecutter.git_project_name}}/.pre-commit-config.yaml

Black and Isort where conflicting, causing a round robin error.
Adding --format black to isort in .precommit-config solved this problem.
closes #264

fix(pre-comm): Add --format black to isort #264

---

tests/test_bake_django.py
{{cookiecutter.git_project_name}}/README.rst
{{cookiecutter.git_project_name}}/pyproject.toml
{{cookiecutter.git_project_name}}/version.toml

A working solution to the semantic version updates was to use pyproject
and version.toml files.  With the same config in setup.cfg it would not
work correctly.  This config works without a setup.py file in the root folder.
closes #254

fix(django): Add pyproject and version.toml #254

---

README.rst
setup.cfg

The version number in README will indicate to users, along with other
information on the page, when the Django Project becomes stable.
closes #218

fix(docs): Add Version to README #218

---

.github/workflows/semantic_release.yaml

Pinning to relekang/python-semantic-release@v7.28.1 fixes
actions using relekang/python-semantic-release@master from
failing.
closes #354

fix(semver): Pin python-semantic-release@v7.28.1 #354

---

docs/requirements.txt

Some docs dependencies need Sphinx<7.0.0.  When these have been updated we can got to 7.0.0
closes #557

docs(deps): Revert to sphinx 6.2.1 #557

---

{{cookiecutter.git_project_name}}/tox.ini

Tests are run against Python 3.11 and also locally 3.12.0a7.
closes #568

chore(tox): Update python test env's #568

---

tests/test_bake_django.py
{{cookiecutter.git_project_name}}/config/settings/local.py

Previously `ALLOWED_HOSTS` and `INTERNAL_IPS` would be configured with
the options passed in with cookiecutter.  The settings files have all
been updated to take their values either from `.env` or `ENV VARS`.
The `LOCAL` settings file has been modified to take a default
`ALLOWED_HOSTS` of `127.0.0.1` if `ALLOWED_HOSTS` is empty.  This makes
setup easy for new django users and will get them up and running
quickly.
All other settings are taking the values supplied in `ALLOWED_HOSTS` as
the default, and the primary source is either `.env` or `ENV_VARS`.
closes #636

chore(settings): Update default Allowed hosts config #636

---

hooks/post_gen_project.py
{{cookiecutter.git_project_name}}/config/settings/base.py

Add the `ADMINS`, `MANAGERS` and `SERVER_EMAIL` to the base settings file.  Added some notes to help users configure these settings.
Add a reminder for the settings to be printed to the console after cookiecutter has created the new project.
closes #645

chore(log): Add admins to settings, message to cookie #645

---

{{cookiecutter.git_project_name}}/core/views/generic/base.py

Add overridden `post` and `get` methods to check for "not_htmx_request_redirect" attribute.
closes #630

chore(htmx): Add overridden methods #630

---

cookiecutter.json
docs/source/reference/reference-project-inputs.rst
tests/test_bake_django.py
{{cookiecutter.git_project_name}}/config/requirements/base.txt
{{cookiecutter.git_project_name}}/config/settings/base.py
{{cookiecutter.git_project_name}}/core/utils/context_processors.py

A constance setting in Admin can provide context to hide the `New User
Signup` link on the login page.
The context is added in `core.utils.context_processors.py` and can be
used in the HTML templates
```
{% if ALLOW_NEW_USER_SIGNUP %}
show signup link
{% endif %}
```
closes #300

feat(admin): Add option to hide new user signups #300

---

.github/workflows/semantic_release.yaml
.github/workflows/test_contribution.yaml
tox.ini

The github actions had deprecated checkout version.  Updated to V4. Updated python setup to V5
closes #744

chore(git): Update actions deps #744

---

.github/workflows/semantic_release.yaml

Ongoing issues with this feature.  Disabled until I get time to dig a bit deeper.  The secret has the correct permissions, but there is still a permission error when the update is pushed.
closes #624

chore(semver): Disable semantic release #624

---

{{cookiecutter.git_project_name}}/config/settings/base.py

django-allauth ACCOUNT_LOGIN_ATTEMPTS_LIMIT has been deprecated for `Rate Limits`.  This PR updates this setting and uses the suggested default ACCOUNT_RATE_LIMITS = ['login_failed'] # Using  (default: "10/m/ip,5/5m/key")
closes #758

chore(auth): Update deprecated settings #758
